version: "3"

services:
  app:
    image: polygon-contract-monitor:latest
    command: gunicorn -b 0.0.0.0:3000 --timeout 999 --threads 12 -k uvicorn.workers.UvicornWorker app.main:server
    environment:
      - APP_NAME=${APP_NAME}
      - DATABASE_URL=mongodb://root:secret@db/app?authSource=admin
      - DATABASE_HOST=db
      - DATA_DIR=/data
      - DOMAIN=localhost
      - ACCESS_TOKEN=${ACCESS_TOKEN}
    volumes:
      - app:/data
    ports:
      - 3000:3000
  db:
    image: mongo:5.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - db:/data/db


volumes:
  db:
  app:
