version: '3.7'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - 443:443
      - 80:80
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    networks:
      - nginx
    logging:
      driver: json-file
      options:
        max-size: 10m

  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
    environment:
      - DEFAULT_EMAIL={{ letsencrypt_email }}
    networks:
      - nginx
    logging:
      driver: json-file
      options:
        max-size: 10m

volumes:
  dhparam:
  conf:
  certs:
  html:
  vhost:

networks:
  nginx:
    external: true
