- name: Set timezone to UTC
  timezone: name=UTC

- name: Enable ufw
  ufw: state=enabled policy=allow direction=outgoing

- name: Allow ssh in
  ufw: rule=limit name=OpenSSH

- name: Disable default in
  ufw: direction=incoming policy=deny

- name: Open ports
  ufw: rule=allow port={{ item }}
  loop:
    - "80"
    - "443"

- name: Reload ufw
  ufw: state=reloaded

- name: Upgrade all packages to the latest version
  apt: upgrade=yes update_cache=yes cache_valid_time=86400 # 1 day

- name: Install apt packages
  apt: pkg={{ item }} state=latest
  loop:
    - mc
    - python3-pip
    - docker.io
    - ntp

- name: Install python packages
  pip: name={{ item }}
  loop:
    - docker
    - jsondiff

- name: Init a new docker swarm
  docker_swarm: state=present

- name: Create nginx docker network
  docker_network: name=nginx scope=swarm driver=overlay

- include_tasks: nginx.yml
