- include_tasks: host.yml
  when: playbook_action == "host"

- include_tasks: nginx.yml
  when: playbook_action == "nginx"

- include_tasks: update.yml
  when: playbook_action == "update"

- include_tasks: delete.yml
  when: playbook_action == "delete"

- include_tasks: test.yml
  when: playbook_action == "test"
